config/routes.rb
Movie::Application.routes.draw do
  root to: 'movies#index'
  get ':id', to: 'movies#show', as: :movie
  get ':id/store/', to: 'movies#store'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
# encoding: utf-8
class MoviesController < ApplicationController
  def index
    @movies = TheMovie.where(params[:search]) if params[:search].present?
  end

  def show
    @movie = TheMovie.find(params[:id])
    redirect_to :root, alert: 'Sorry... movie not found.' unless @movie
  end

  def store
    candidates = PlayMovie.where(generic(params[:name]))
    if candidates
      match_ids = match(candidates, params[:name])
      if match_ids.any?
        match_ids.each do |id|
          movie = PlayMovie.find(id)
          if movie
            if director(movie) == transformers(params[:director]) || year(movie) == params[:year]
              @google = price(movie, id)
              render partial: 'store' and return
            end
          end
        end
      end
      @related = alternative(candidates)
    end
    render partial: 'store'
  end

private
  # -Parse-

  def match(candidates, seeking)
    transformers(seeking)
    ids = []

    candidates.css('.card').each do |candidate|
      next unless name = candidate.at_css('.title').text

      if transformers(name) == seeking
        ids << candidate['data-docid'][6..-1].to_s
      end
    end
    ids
  end

  def director(movie)
    movie.css('.details-section.cast-credit tr').each do |tr|
      next unless label = tr.at_css('.cc-row-label').text

      if clear(label) == 'director'
        name = tr.at_css('.cc-row-contents a').text
        return transformers(name)
      end
    end
    ''
  end

  def year(movie)
    date = movie.at_css('.details-info .info-container .document-subtitle[itemprop=datePublished]').text
    return '' unless date.present?
    clear(date)[-4..-1]
  end

  def price(movie, id)
    price = movie.at_css('.details-wrapper .details-info .details-actions .buy-button-container .price')
    google = {
      url:   PlayMovie.base_uri + "/movies/details?id=#{id.to_s}",
      price: price.css('span').last.text }
  end

  def alternative(candidates)
    related = []
    candidates.css('.card').first(3).each do |candidate|
      break unless candidate

      related << hash = {
        url:    PlayMovie.base_uri + "/movies/details?id=#{candidate['data-docid'][6..-1].to_s}",
        name:   space(candidate.at_css('.title').text),
        price:  space(candidate.at_css('.price-container .price').text),
        poster: candidate.at_css('.cover-image')['src'] }
    end
    related
  end

  # -Regex-

  def space(line)
    line.gsub(/^\s+|\s+$/,'') if line.present?
  end

  def clear(line)
    line.downcase.gsub(/\W/,'') if line.present?
  end

  def generic(line)
    line.downcase.gsub(/\bpart (\d|i)+\b/,'') if line.present?
  end

  def transformers(line)
    return unless line.present?
    line.downcase!
    line.gsub!(/^\s*the\b\s/,'')
    line.gsub!(/&/,'and')
    line.gsub!(/\bpart \d\b/, 'part 1'=>1, 'part 2'=>2, 'part 3'=>3)
    line.gsub!(/\bpart i+\b/, 'part i'=>1, 'part ii'=>2, 'part iii'=>3)
    line.gsub!(/[\W\_]+/,'')
    line
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
    <a class='close' data-dismiss='alert'>×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Seeker</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='container'>
      <div class='header'>
        <h1>
          <%= link_to 'The Seeker', :root %><small> of Truth</small>
        </h1>
      </div>

      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <div>
      <%= javascript_include_tag 'application' %>
      <%= yield :javascript %>
    </div>
  </body>
</html>

app/views/movies/_actor.html.erb
<% pic = actor['profile_path'] ? TheMovie.poster(actor['profile_path'],'w45') : 'profile.jpg' %>
<% url = "http://www.themoviedb.org/person/#{actor['id']}" %>

<div class='actor'>
  <div class='pic'>
    <%= link_to (image_tag pic, class: 'img-polaroid'), url %>
  </div>

  <div class='names'>
    <b><%= link_to actor['name'], url %></b>
    <br>
    <%= actor['character'] %>
  </div>
</div>

app/views/movies/_movie.html.erb
<% pic = movie['poster_path'] ? TheMovie.poster(movie['poster_path'],'w92') : 'small.jpg' %>
<% url = movie_path(movie['id']) %>

<div class='movie'>
  <div class='pic'>
    <%= link_to (image_tag pic, class: 'img-polaroid'), url %>
  </div>

  <div class='movie-info'>
    <p><%= link_to movie['title'], url %></p>

    <span class='badge year'>
      <%= movie['release_date'][0..3] %>
    </span>

    <div class='ratings'>
      <span class='badge average'>
        <div class='icon star'></div>
        <%= movie['vote_average'] %>
      </span>
      <span class='badge count'>
        <%= movie['vote_count'] %>
        <div class='icon users'></div>
      </span>
    </div>
  </div>
</div>

app/views/movies/_related.html.erb
<div class='related'>
  <div class='pic'>
    <%= link_to (image_tag related[:poster], class: 'img-polaroid'), related[:url] %>
  </div>

  <div class='related-info'>
    <p><%= link_to related[:name], related[:url] %></p>
    <%= link_to related[:price], related[:url], class: 'price-button upper' %>
  </div>
</div>

app/views/movies/_request.html.erb
<% content_for :javascript do %>
  <script type='text/javascript'>
    GetPrices(
      '<%= params[:id] %>',
      '<%= CGI.escape(@movie.name) %>',
      '<%= CGI.escape(@movie.director) if @movie.director %>',
      '<%= CGI.escape(@movie.year) if @movie.year %>');
  </script>
<% end %>

app/views/movies/_store.html.erb
<div id='buy_container'>
  <% if @google && @google[:url].present? && @google[:price].present? %>
    <%= link_to @google[:price], @google[:url], class: 'buy-button upper' %>
  <% else %>
    <a class='buy-button upper'>Not available</a>
  <% end %>
</div>

<% if @related.present? %>
  <div id='related_container'>
    <p class='upper'>Look at related</p>
    <%= render partial: 'related', collection: @related %>
  </div>
<% end %>

app/views/movies/index.html.erb
<%= form_tag root_path, method: 'get', id: 'seeker' do %>
  <div class='input-append'>
    <%= text_field_tag :search, params[:search], placeholder: 'Serenity .....', class: 'span6' %>
    <%= submit_tag 'Search', name: nil, class: 'btn' %>
  </div>
<% end %>

<div id='movies_container'>
  <div class='movie-logo upper'>
    What kind of movies do you like..?
  </div>
</div>

app/views/movies/index.js.erb
$('#movies_container').html("<%= escape_javascript( render(partial: 'movie', collection: @movies) || raw("<div class='movie-logo no-one upper'>Sorry... we couldn't find any movies</div>") ) %>");

app/views/movies/show.html.erb
<div class='top'>
  <%= link_to @movie.name, "http://www.themoviedb.org/movie/#{params[:id]}" %>
</div>

<div class='side'>
  <div class='play'>
    <div class='img-polaroid'>
      <%= @movie.middle ? (link_to (image_tag @movie.middle), @movie.large) : (image_tag 'middle.jpg') %>
    </div>

    <div class='ratings'>
      <span class='badge average'>
        <div class='icon star'></div>
        <%= @movie.rating %>
      </span>
      <span class='badge count'>
        <%= @movie.count %>
        <div class='icon users'></div>
      </span>
    </div>

    <div class='store_container'>
      <div class='google-logo'></div>
      <div id='store_result'>
        <div id='buy_container'>
          <%= render 'request' %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @movie.backdrop.present? %>
  <div class='backdrop'>
    <%= image_tag @movie.backdrop %>
  </div>
<% end %>

<div class='info'>
  <div class='tagline upper'>
    <% if @movie.tagline.present? %>
      <%= @movie.tagline %>
    <% end %>
  </div>
  
  <% if @movie.overview.present? %>
    <div class='section'>
      <p class='upper'>Synopsis</p>
      <%= @movie.overview %>
    </div>
  <% end %>

  <% if @movie.year.present? %>
    <div class='section'>
      <span class='year upper'>Year</span>
      <%= @movie.year %>
    </div>
  <% end %>

  <% if @movie.director.present? %>
    <div class='section'>
      <span class='director upper'>Director</span>
      <%= @movie.director %>
    </div>
  <% end %>

  <% if @movie.actors.any? %>
    <div class='section'>
      <p class='upper'>Actors</p>
      <div class='actors-container'>
        <%= render partial: 'actor', collection: @movie.actors %>
      </div>
    </div>
  <% end %>
</div>

<div class='endline'></div>